workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
  - build
  - deploy

cache:
  key: gradle-cache
  paths:
    - .gradle/

build:
  image: gradle:jdk17
  stage: build
  rules:
    - if: $CI_COMMIT_TAG
  before_script:
    - GRADLE_USER_HOME="$(pwd)/.gradle"
    - export GRADLE_USER_HOME
  script:
    - gradle --build-cache distZip distTar
    - mv app/build/distributions/app.zip "${CI_PROJECT_NAME}-${CI_COMMIT_TAG}.zip"      
    - mv app/build/distributions/app.tar "${CI_PROJECT_NAME}-${CI_COMMIT_TAG}.tar"  
  artifacts:    
    paths:      
      - "*.zip"  
      - "*.tar"
    expire_in: 1 day

deploy:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "running release_job for $TAG"
  release:
    tag_name: $CI_COMMIT_TAG
    name: Release $CI_PROJECT_NAME-$CI_COMMIT_TAG
    description: Release notes for $CI_PROJECT_NAME-$CI_COMMIT_TAG
    ref: $CI_COMMIT_SHA
    assets:
      links:
        - name: $PROJECT_NAME.zip
          url: $CI_PROJECT_URL/-/jobs/$CI_JOB_ID/artifacts/raw/app/build/distributions/$PROJECT_NAME.zip
        - name: $PROJECT_NAME.tar
          url: $CI_PROJECT_URL/-/jobs/$CI_JOB_ID/artifacts/raw/app/build/distributions/$PROJECT_NAME.tar
