workflow:
  rules:
    - if: $CI_COMMIT_TAG
      when: always
    - when: never

stages:
  - build
  - release

variables:
  PROJECT_NAME: $CI_PROJECT_NAME-$CI_COMMIT_TAG

cache:
  key: gradle-cache
  paths:
    - .gradle/

build:
  stage: build
  image: gradle:jdk17
  before_script:
    - GRADLE_USER_HOME="$(pwd)/.gradle"
    - export GRADLE_USER_HOME
  script:
    - gradle --build-cache distZip distTar
    - mkdir dist
    - mv ./app/build/distributions/app.zip ./dist/$PROJECT_NAME.zip
    - mv ./app/build/distributions/app.tar ./dist/$PROJECT_NAME.tar
  artifacts:
    paths:
      - "./dist"
    expire_in: 1 day

release:
  stage: release
  image: gitlab/glab
  needs:
    - build
  script:
    - echo "running release_job for $PROJECT_NAME"
    - glab auth login --hostname $CI_SERVER_HOST --job-token $CI_JOB_TOKEN
    - glab release create "$CI_COMMIT_TAG" ./dist/*
